# Generated by Django 4.2.6 on 2023-10-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='default', upload_to='pics'),
            preserve_default=False,
        ),
    ]
